# permissions for end users to view githubusercodespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubusercodespace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: knot-github-codespace
    app.kubernetes.io/part-of: knot-github-codespace
    app.kubernetes.io/managed-by: kustomize
  name: githubusercodespace-viewer-role
rules:
- apiGroups:
  - codespaces.user.github.nttdata.com
  resources:
  - githubusercodespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - codespaces.user.github.nttdata.com
  resources:
  - githubusercodespaces/status
  verbs:
  - get
